### ISSUE TITLE
Invalid literal: "OK"

### ISSUE THREAD

**Issue by Artur-** [vaadin/vscode-plugin#27]
This apparently happens or can happen as part of any operation (reported for duplicate and add call)
```
elemental.json.JsonException: Invalid literal: "OK"
at elemental.json.impl.JsonTokenizer.getValueForLiteral(JsonTokenizer.java:312)
    at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:177)
    at elemental.json.impl.JreJsonFactory.parse(JreJsonFactory.java:64)
    at elemental.json.Json.parse(Json.java:53)
    at com.vaadin.copilot.ide.CopilotIDEPlugin.sendRestSync(CopilotIDEPlugin.java:339)
    at com.vaadin.copilot.ide.CopilotIDEPlugin.send(CopilotIDEPlugin.java:318)
    at com.vaadin.copilot.ide.CopilotIDEPlugin.writeFile(CopilotIDEPlugin.java:214)
    at com.vaadin.copilot.ProjectManager.writeFile(ProjectManager.java:178)
```

Vaadin: 24.5.0
IDE Plugin: 1.0.7 VS Code

**Comment by Artur-** [comment]
This is about parsing the response from the VS Code plugin
